"""energy_house.py
Production Railway Volume Storage for Flexible X Bot.
- Stores ALL valid cookies as standardized Netscape .txt files
- Anonymous naming: {email}_{plan}_{country}_{seq}.txt
- Sequential counter tracked in SQLite to prevent collisions
- Admin backup/clear operations on /mnt/data/archive/
- User data files live directly in /mnt/data/ (never deleted by clear)
"""
import os
import sqlite3
import hashlib
import datetime
from pathlib import Path
from typing import Optional, Tuple

# === RAILWAY VOLUME PATHS ===
VOLUME_ROOT = Path("/mnt/data")
ARCHIVE_ROOT = VOLUME_ROOT / "archive"
DB_PATH = VOLUME_ROOT / "archive.db"
HASHES_FILE = VOLUME_ROOT / "hashes.txt"

# Persistent user data files (live directly in volume root, NEVER touched by clear)
USERS_FILE = VOLUME_ROOT / "users.txt"
REFERRALS_FILE = VOLUME_ROOT / "referrals.json"
RATE_LIMITS_FILE = VOLUME_ROOT / "rate_limits.json"

_conn: Optional[sqlite3.Connection] = None


def _ensure_dirs():
    """Create all required directories on the Railway volume."""
    try:
        ARCHIVE_ROOT.mkdir(parents=True, exist_ok=True)
        VOLUME_ROOT.mkdir(parents=True, exist_ok=True)
    except Exception as e:
        print(f"⚠️ Could not create volume dirs: {e}")


def init_energy_house() -> None:
    """Initialize storage paths, directories, and SQLite database."""
    global _conn
    _ensure_dirs()

    if not USERS_FILE.exists():
        USERS_FILE.touch()
    if not REFERRALS_FILE.exists():
        REFERRALS_FILE.write_text("{}")
    if not RATE_LIMITS_FILE.exists():
        RATE_LIMITS_FILE.write_text("{}")
    if not HASHES_FILE.exists():
        HASHES_FILE.touch()

    if _conn is not None:
        return

    _conn = sqlite3.connect(str(DB_PATH), check_same_thread=False)
    cur = _conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS stored_files (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            message_id INTEGER,
            user_id INTEGER,
            original_name TEXT,
            storage_path TEXT,
            mime TEXT,
            md5_hash TEXT UNIQUE,
            size INTEGER,
            stored_at TEXT
        )
    """)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS file_counter (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            next_seq INTEGER NOT NULL DEFAULT 1
        )
    """)
    cur.execute("INSERT OR IGNORE INTO file_counter (id, next_seq) VALUES (1, 1)")
    _conn.commit()


def _md5_of_bytes(b: bytes) -> str:
    m = hashlib.md5()
    m.update(b)
    return m.hexdigest()


def _sanitize_anonymous_part(value: str, fallback: str = "unknown") -> str:
    if not value or value == "Unknown":
        return fallback
    clean = "".join(c for c in value if c.isalnum() or c in ".-_@").strip()
    return clean[:80] or fallback


def _get_next_sequence() -> int:
    global _conn
    if _conn is None:
        init_energy_house()
    cur = _conn.cursor()
    cur.execute("UPDATE file_counter SET next_seq = next_seq + 1 WHERE id = 1")
    cur.execute("SELECT next_seq FROM file_counter WHERE id = 1")
    row = cur.fetchone()
    _conn.commit()
    return row[0] - 1 if row else 1


def convert_cookies_to_netscape(cookie_dict: dict) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by Flexible X Bot", ""]
    for name, value in cookie_dict.items():
        if not value:
            continue
        domain = ".netflix.com"
        flag = "TRUE"
        path = "/"
        secure = "TRUE"
        expiration = "0"
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def store_file_from_bytes(
    file_bytes: bytes,
    original_name: Optional[str],
    user_id: int,
    message_id: Optional[int],
    mime: Optional[str],
    account_info: Optional[dict] = None,
    cookie_dict: Optional[dict] = None
) -> Tuple[str, bool]:
    global _conn
    if _conn is None:
        init_energy_house()

    if cookie_dict:
        netscape_content = convert_cookies_to_netscape(cookie_dict)
        store_bytes = netscape_content.encode("utf-8")
    else:
        store_bytes = file_bytes

    md5_hash = _md5_of_bytes(store_bytes)

    cur = _conn.cursor()
    cur.execute("SELECT storage_path FROM stored_files WHERE md5_hash = ?", (md5_hash,))
    row = cur.fetchone()
    if row:
        return row[0], False

    email = _sanitize_anonymous_part((account_info or {}).get("email"), "noemail")
    plan = _sanitize_anonymous_part((account_info or {}).get("plan"), "unknown")
    country = _sanitize_anonymous_part((account_info or {}).get("country"), "XX")
    seq = _get_next_sequence()
    filename = f"{email}_{plan}_{country}_{seq}.txt"

    now = datetime.datetime.utcnow()
    subdir = ARCHIVE_ROOT / f"{now:%Y}" / f"{now:%m}" / f"{now:%d}"
    subdir.mkdir(parents=True, exist_ok=True)
    final_path = subdir / filename

    tmp_path = subdir / f".tmp-{md5_hash[:12]}"
    with open(tmp_path, "wb") as f:
        f.write(store_bytes)
    os.replace(tmp_path, final_path)

    size = final_path.stat().st_size

    cur.execute(
        """INSERT INTO stored_files 
           (message_id, user_id, original_name, storage_path, mime, md5_hash, size, stored_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
        (message_id, user_id, original_name, str(final_path), mime, md5_hash, size, now.isoformat())
    )
    _conn.commit()

    try:
        with open(HASHES_FILE, "a") as f:
            f.write(md5_hash + "\n")
    except Exception:
        pass

    return str(final_path), True


def clear_archive() -> int:
    global _conn
    deleted_count = 0
    if not ARCHIVE_ROOT.exists():
        return 0
    for item in ARCHIVE_ROOT.rglob("*"):
        if item.is_file():
            try:
                item.unlink()
                deleted_count += 1
            except Exception:
                pass
    for dirpath in sorted(ARCHIVE_ROOT.rglob("*"), reverse=True):
        if dirpath.is_dir():
            try:
                dirpath.rmdir()
            except OSError:
                pass
    if _conn is not None:
        cur = _conn.cursor()
        cur.execute("UPDATE file_counter SET next_seq = 1 WHERE id = 1")
        _conn.commit()
    return deleted_count
